# Generated by Django 5.2.3 on 2025-08-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_contact',
            field=models.CharField(blank=True, help_text="Guardian's phone number or email", max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
