# Generated by Django 5.2.3 on 2025-08-10 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian_name',
        ),
    ]
