# Generated by Django 5.2.3 on 2025-10-11 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="A concise title for the event (e.g., 'Term 1 Mid-Term Exams')", max_length=200)),
                ('start_time', models.DateTimeField(help_text='The start date and time of the event')),
                ('end_time', models.DateTimeField(help_text='The end date and time of the event')),
                ('event_type', models.CharField(choices=[('EXAM', 'Exam'), ('FEE_DEADLINE', 'Fee Deadline'), ('HOLIDAY', 'Holiday'), ('SCHOOL_EVENT', 'School Event'), ('ACADEMIC_TERM', 'Academic Term')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional: More details about the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='calendar_ev_start_t_065f54_idx')],
            },
        ),
    ]
