# Generated by Django 5.2.3 on 2025-10-12 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, help_text="Identifier to group recurring events (e.g., 'schedule-123')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('EXAM', 'Exam'), ('FEE_DEADLINE', 'Fee Deadline'), ('HOLIDAY', 'Holiday'), ('SCHOOL_EVENT', 'School Event'), ('ACADEMIC_TERM', 'Academic Term'), ('CLASS_SCHEDULE', 'Class Schedule')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['group_id'], name='calendar_ev_group_i_a4b906_idx'),
        ),
    ]
