# Generated by Django 5.2.3 on 2025-07-16 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Class name, e.g., 'Grade 4 West'", max_length=100, unique=True)),
                ('level', models.CharField(help_text="Class level, e.g., 'Grade 4'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_in_charge', models.ForeignKey(blank=True, help_text='Teacher responsible for this class', limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_in_charge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['level'], name='classes_cla_level_6d5707_idx'), models.Index(fields=['teacher_in_charge'], name='classes_cla_teacher_b0fc09_idx'), models.Index(fields=['created_at'], name='classes_cla_created_ec5000_idx')],
            },
        ),
    ]
