# Generated by Django 5.2.3 on 2025-08-03 20:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('exams', '0002_alter_term_options_term_academic_year_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True, help_text='Date when the invoice was generated')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount (sum of all items)', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far', max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', help_text='Current payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='Class the student was in when invoice was generated', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='classes.class')),
                ('student', models.ForeignKey(help_text='Student this invoice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.studentprofile')),
                ('term', models.ForeignKey(help_text='Academic term this invoice applies to', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='exams.term')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="Description of the fee item, e.g., 'Term 1 Tuition'", max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this specific item', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['invoice', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_date', models.DateField(help_text='Date the payment was made')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card')], help_text='Method used for payment', max_length=20)),
                ('reference_code', models.CharField(blank=True, help_text='Transaction ID or reference code (optional)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.invoice')),
                ('recorded_by', models.ForeignKey(help_text='Admin/staff who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the fee type, e.g., 'Standard Tuition Fee', 'Bus Transportation Fee'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the fee')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fee amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='Class this fee applies to', on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='classes.class')),
                ('term', models.ForeignKey(help_text='Academic term this fee applies to', on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='exams.term')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['classroom', 'term', 'name'],
                'indexes': [models.Index(fields=['classroom', 'term'], name='fees_feestr_classro_7158d3_idx'), models.Index(fields=['created_at'], name='fees_feestr_created_1812fa_idx')],
                'unique_together': {('name', 'classroom', 'term')},
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student', 'term'], name='fees_invoic_student_4a40f1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='fees_invoic_status_1e2496_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='fees_invoic_due_dat_924943_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='fees_invoic_issue_d_e9d9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_date'], name='fees_paymen_invoice_f1eb10_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='fees_paymen_payment_872f14_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['recorded_by'], name='fees_paymen_recorde_b689cc_idx'),
        ),
    ]
