# Generated by Django 5.2.3 on 2025-08-03 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-academic_year', 'name']},
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.IntegerField(default='2024', help_text='Academic year (e.g., 2025)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_year', 'name')},
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_academic_year_term'),
        ),
    ]
