# Generated by Django 5.2.3 on 2025-08-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='date_of_hire',
            field=models.DateField(blank=True),
        ),
    ]
