# Generated by Django 5.2.3 on 2025-08-17 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_alter_term_options_term_academic_year_and_more'),
        ('students', '0004_remove_studentprofile_guardian_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Report title, e.g., 'Term 1 Mid-Term Report' or 'Term 1 Final Report Card'", max_length=200)),
                ('report_data', models.JSONField(help_text='Complete serialized JSON of the report card at generation time')),
                ('is_published', models.BooleanField(default=False, help_text='Controls visibility for parents and students')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when report was generated')),
                ('exam', models.ForeignKey(blank=True, help_text='Specific exam (optional - for single-exam reports vs end-of-term summaries)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='exams.exam')),
                ('generated_by', models.ForeignKey(blank=True, help_text='User who generated this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student for whom this report is generated', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='students.studentprofile')),
                ('term', models.ForeignKey(help_text='Academic term for this report', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='exams.term')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-generated_at', 'student__admission_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('exam__isnull', False)), fields=('student', 'term', 'exam'), name='unique_student_term_exam_report'), models.UniqueConstraint(condition=models.Q(('exam__isnull', True)), fields=('student', 'term'), name='unique_student_term_summary_report')],
            },
        ),
    ]
