# Generated by Django 5.2.3 on 2025-07-16 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the subject (e.g., Mathematics, English)', max_length=100)),
                ('code', models.CharField(help_text='Unique subject code (e.g., MATH101, ENG201)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the subject', null=True)),
                ('level', models.CharField(help_text='Grade level or academic level (e.g., Grade 1, Grade 2, High School)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the subject was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the subject was last updated')),
                ('teacher_in_charge', models.ForeignKey(blank=True, help_text='Teacher responsible for this subject', limit_choices_to={'is_active': True, 'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_in_charge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['level', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'level'), name='unique_subject_per_level')],
            },
        ),
    ]
