# Generated by Django 5.2.3 on 2025-09-23 00:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='The year this budget applies to (e.g., 2025)', validators=[django.core.validators.MinValueValidator(2020)])),
                ('month', models.IntegerField(help_text='The month this budget applies to (1=Jan, 12=Dec)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('amount', models.DecimalField(decimal_places=2, help_text='The budgeted amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='expenses.expensecategory')),
            ],
            options={
                'ordering': ['year', 'month', 'category__name'],
                'unique_together': {('category', 'year', 'month')},
            },
        ),
    ]
