# Generated by Django 5.2.3 on 2025-08-04 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('exams', '0002_alter_term_options_term_academic_year_and_more'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Time slot identifier, e.g., 'Period 1', 'Break Time'", max_length=100, unique=True)),
                ('start_time', models.TimeField(help_text='Start time of the period')),
                ('end_time', models.TimeField(help_text='End time of the period')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], help_text='Day of the week for this class session', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='The class/classroom for this schedule entry', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='classes.class')),
                ('subject', models.ForeignKey(help_text='The subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='subjects.subject')),
                ('teacher', models.ForeignKey(help_text='Teacher assigned to teach this session', limit_choices_to={'is_active': True, 'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(help_text='Academic term for this schedule entry', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='exams.term')),
                ('timeslot', models.ForeignKey(help_text='Time slot for this class session', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedules.timeslot')),
            ],
            options={
                'verbose_name': 'Schedule Entry',
                'verbose_name_plural': 'Schedule Entries',
                'ordering': ['day_of_week', 'timeslot__start_time'],
                'indexes': [models.Index(fields=['classroom', 'term'], name='schedules_s_classro_073136_idx'), models.Index(fields=['teacher', 'term'], name='schedules_s_teacher_4b6045_idx'), models.Index(fields=['day_of_week', 'timeslot'], name='schedules_s_day_of__a63e2a_idx')],
                'constraints': [models.UniqueConstraint(fields=('term', 'classroom', 'timeslot', 'day_of_week'), name='unique_classroom_timeslot_per_term_day')],
            },
        ),
    ]
